<center>
<div class="alert alert-block alert-info">
    <h1> </h1>
    <h1><font size="+3"> <b> Math340 HW4 </b> </font></h1>
    <h1><font size="+3"> <b> Programming in Mathematics </b> </font></h1>
    <h1><font size="+3"> <b> Due February 21th, 2025 </b> </font></h1>
    
</div>
</center>

<br>



<center>
<font size="+2">
Department of Mathematics and Statistics <br> <br>
San Diego State University <br> <br>
Spring 2025
</font>
</center>








## Meg Bucich

## 1. Summary

(Problem 1) We were tasked with building a 7x7 matrix that has entries of the cosine similarities of ROYGBIV against every color. The diagonal would be 1 because the cosine similarity is the dot product of the two vectors divided by the magnitudes of the two vectors multiplied together. But, if you take the dot product of two equal vectors (i.e of the same color), its equal to the multiplication of their magnitudes. This means the cosine similarity is 1 because any number divided by itself is 1. This makes sense because cos(0) = 1, where the angle represents the angle between the two vectors. (Problem 2) We are asked to discuss the differences between rounding and truncation; in short, decimal approximations are handled slightly differently. (Problem 3) We were given a code that extracted the main article from a Wikipedia page called the Butterfly effect. We were tasked with extending the code so that it counts the number of times the phrase 'butterfly effect' appears in the article.

## 2. Methodolody 

(Problem 1) To create the 7x7 cosine similarity matrix, I broke it up into two segments. Step 1 is to compute each cosine similarity. This requires 3 quantities and 3 functions. We need the dot product and the magnitude of both vectors. I created a function for each of those, then made my final function a combination of the two to get a cosine similarity function. This works for any two vectors. The 7 colors we are concerned with were written in vector form to be used in the function. Step 2 was to create the matrix. I started with an empty 7x7 matrix and used two for loops to fill the entries with the cosine similarities. I made sure my loop gets every single combination of all 7 colors, a total of 49, and took each of their operations and added it to the appropriate entry of the matrix. I used the round function to only put 3 decimals in each entry. (Problem 3) to find the number of times the phrase 'butterfly effect' appears in the article, I started by adding .lower() to the variable that extracted the words to not have to worry about upper/lower case. I then defined "freq" to be zero. I used one loop to see if one element entry was "butterfly" AND the second entry was "effect", then it would add 1 to the frequency count. Finally, it printed the frequency after iterating through every word. 

## 3. Code and Results

### Results for Q1

In [20]:
import numpy as np
red = [255,0,0]
orange = [255,165,0]
yellow = [255,255,0]
green = [0,128,0]
blue = [0,0,255]
indigo = [75,0,255]
violet = [128,0,128]

def dot_product(a,b):
    products = []
    for i in range(len(b)):
        prod = a[i]*b[i]
        products.append(prod)
    return(sum(products))


def magnitude(a):
    squares = []
    for i in range(len(a)):
        a_squared = a[i]**2
        squares.append(a_squared)
    
    return((sum(squares)**(1/2)))
    
def cosine_sim(a,b):
    return dot_product(a,b) / (magnitude(a)*magnitude(b))
    
colors = [red, orange, yellow, green, blue, indigo, violet]
cosine_matrix = np.zeros((7,7))
for i in range(len(colors)):
    for j in range(len(colors)):
        dot = cosine_sim(colors[i],colors[j])
        cosine_matrix[i,j] = round(dot,3)
print("Cosine Similarity Matrix for ROYGBIV:\n\n" , cosine_matrix)

Cosine Similarity Matrix for ROYGBIV:

 [[1.    0.84  0.707 0.    0.    0.282 0.707]
 [0.84  1.    0.978 0.543 0.    0.237 0.594]
 [0.707 0.978 1.    0.707 0.    0.2   0.5  ]
 [0.    0.543 0.707 1.    0.    0.    0.   ]
 [0.    0.    0.    0.    1.    0.959 0.707]
 [0.282 0.237 0.2   0.    0.959 1.    0.878]
 [0.707 0.594 0.5   0.    0.707 0.878 1.   ]]


### Results for Q2

#### Using information from #1b and lecture notes, explore the ideas of rounding and truncation.

Rounding and truncation are both methods of decimal approximations but have different approaches. When rounding a number to n digits, we consider whether the (n+1)th >= 5 or < 5. This tells us if we are going to round up or down. Rounding is a generally more accurate method of decimal approximation than truncation. Truncation has a a similar approach but does not consider the (n+1)th digit and cuts it off without adjusting the nth digit. Truncation can cause errors that progress during lengthy calcuations. 

### Results for Q3

Extend the given code to compute the frequency of the term "butterfly effect" within the Wikipedia article titled "Butterfly Effect"

In [41]:
import requests
from bs4 import BeautifulSoup
import re

url = "https://en.wikipedia.org/wiki/Butterfly_effect"
response = requests.get(url)
if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')
    content = soup.find(id='mw-content-text')
    text = content.get_text(" ",strip=True).lower() #so we dont have to worry about upper vs lower  
    text = re.sub(r'[^\w\s]', '', text)
    #my method of counting frequencies only got the main text. this line allows to count the cases
    #that the phrase shows up along the side of the page.
    words = text.split()
    freq = 0
    n = len(words)
    for i in range(n-1): #in case 'butterfly' were to be the last word in the article, we want to avoid indexing out of range for i+1
        if words[i] == "butterfly" and (words[i+1] == "effect" or words[i+1] == "effects"):
            freq += 1
            print(f"{words[i]} {words[i+1]}, ",end="")
    print("\nThe phrase 'butterfly effect' appears", freq, "times in the Wikipedia article titled 'Butterfly Effect")         
else: 
    print("Failed to fetch the Wikipedia page.")

butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effects, butterfly effect, butterfly effects, butterfly effect, butterfly effect, butterfly effect, butterfly effects, butterfly effect, butterfly effect, butterfly effects, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effects, butterfly effect, butterfly effects, butterfly effect, butterfly effect, butterfly effects, butterfly effects, butterfly effects, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, butterfly effect, b