In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

**Problem 1**: For a $n\times n$ unitary matrix $U$, so that $U^{-1}=U^{\dagger}$ show that 

$$
\left|\left|U{\bf x}\right|\right| = \left|\left|{\bf x}\right|\right|, ~ {\bf x}\in \mathbb{C}^{n}
$$

Please explain in words what this means.  

This means that the size of the vector X is not affected when it's multipled by a matrix because it has a size of 1 unit. 

**Problem 2**: For the matrix $A:\mathbb{R}^{2}\rightarrow \mathbb{R}^{3}$ where 

$$
A = \begin{pmatrix} 1 & 3 \\ 3 & 2 \\ 1 & 2 \end{pmatrix}
$$

using `np.linalg.svd`, numerically compute its full and economy SVD.

* Explain, as in literally show, the differences between the economy and full SVD.  
* Using `np.linalg.norm` test the orthonomality of the orthogonal matrices in your SVD.  Comment on what you find.  

In [9]:
A = np.array([[1,3],[3,2],[1,2]])
full_SVD = np.linalg.svd(A,full_matrices =True)
econ_SVD = np.linalg.svd(A,full_matrices=False)

In [18]:
U_full,D_full,V_full = full_SVD
U_econ,D_econ,V_econ = econ_SVD
print("Full SVD")
print("U:\n", U_full,"\nD:\n ", D_full,"\nV: \n", V_full)
print("Economy SVD")
print("U:\n", U_econ,"\nD:\n ", D_econ,"\nV: \n", V_econ)


Full SVD
U:
 [[-0.59347314  0.63668312 -0.49236596]
 [-0.67666349 -0.72593045 -0.12309149]
 [-0.43579372  0.26011458  0.86164044]] 
D:
  [5.0400153  1.61190749] 
V: 
 [[-0.60699365 -0.79470668]
 [-0.79470668  0.60699365]]
Economy SVD
U:
 [[-0.59347314  0.63668312]
 [-0.67666349 -0.72593045]
 [-0.43579372  0.26011458]] 
D:
  [5.0400153  1.61190749] 
V: 
 [[-0.60699365 -0.79470668]
 [-0.79470668  0.60699365]]


**Problem 3**: For given real-valued, $n\times n$ square matrix $A$ with SVD $A=U\Sigma V^{T}$, if we order the singular values $\sigma_{j}$ such that $\sigma_{1}\geq \sigma_{2}\geq \cdots \geq \sigma_{n}$, then we define its *condition number*, say $c(A)$, to be 

$$
c(A) = \frac{\sigma_{1}}{\sigma_{n}}
$$

Note, if $A$ is not of full rank then $\sigma_{n}=0$ and $c(A)=\infty$.

For $2 \leq n \leq 30$, using `np.random.randn` which generates random matrices using a normal distribution, find the average condition number as a function of $n$.  Plot your results and comment upon them.  Use the code skeleton below to get started.  

In [ ]:
nvals = np.arange(2,31) # range of n-vals
nsamples = # how many different random samples per dimension do we want to generate?  how do your results change as you change this number?
average_condition_numbers = np.zeros(nvals.size)
for cnt, nval in enumerate(nvals):
    tot = 0
    for jj in range(nsamples):
        Amat = np.random.randn(nval, nval)
        # find the svd of Amat
        if : # don't include matrices that don't have full rank
            # update your average here 
            # keep track of how many terms you're including in your average
    average_condition_numbers[cnt] /= tot # make sure you compute an average

plt.plot(average_condition_numbers)
plt.xlabel(r"$n$")


**Problem 4** (Graduate/Extra Credit): When using the economy SVD, only one of the products $U^{\dagger}U$ and $UU^{\dagger}$ is guaranteed to be the identity,
while the other is a projection. Which is which and why?

**Problem 5** (Graduate/Extra Credit): For $m\times n$ complex valued matrix $A$, we define its *Frobenius norm* $\left|\left|A\right|\right|_{F}$ via the formula

$$
\left|\left|A\right|\right|^{2}_{F} = \text{tr}\left(A^{\dagger}A \right).
$$

Using the SVD $A = U\Sigma V^{\dagger}$, show that 

$$
\left|\left|A\right|\right|^{2}_{F} = \sum_{l=1}^{r}\sigma_{l}^{2}, ~ r = \text{rank}(A).
$$